{
  "formatVersion": "1.1",
  "component": {
    "group": "test.com.meituan.robust",
    "module": "auto-patch-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "auto-patch-plugin-1.0.0.jar",
          "url": "auto-patch-plugin-1.0.0.jar",
          "size": 2896738,
          "sha512": "4796fc473fd7c1aa93a521f2d12b71fcd646e0c11a91c83c77e7d556d7fc2a75fb4c9b313bdf402499419af42acba5173ddf58ee2d6e77f25a1530a370e5b239",
          "sha256": "bbda1d7bf404c72903732cb757e6fed88259b3f0f16c9a3f774755b9c3eb62b3",
          "sha1": "78ec5a3b2480d1f17a1a4751a7ee8d8a5170bb8b",
          "md5": "063f5f7e101e25819d73292d9e925acc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "test.com.meituan.robust",
          "module": "autopatchbase",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "auto-patch-plugin-1.0.0.jar",
          "url": "auto-patch-plugin-1.0.0.jar",
          "size": 2896738,
          "sha512": "4796fc473fd7c1aa93a521f2d12b71fcd646e0c11a91c83c77e7d556d7fc2a75fb4c9b313bdf402499419af42acba5173ddf58ee2d6e77f25a1530a370e5b239",
          "sha256": "bbda1d7bf404c72903732cb757e6fed88259b3f0f16c9a3f774755b9c3eb62b3",
          "sha1": "78ec5a3b2480d1f17a1a4751a7ee8d8a5170bb8b",
          "md5": "063f5f7e101e25819d73292d9e925acc"
        }
      ]
    }
  ]
}
